#include <stdbool.h>
/*
Original code by Ruud Helderman ("How to program a text adventure in C")
For the game "THE SPIRIT WITHIN US" Alessandro Ielo added:
.explanation: obj->description is used to describe the whole scene and obj->explanation to name individual objects.
.originalLocation: defines the original location of the object (check misc.c)
.power: the amount of food energy (check executeEat in inventory2.c).
.animal: defines whether an object is an animal (check damage.c).
.sector: defines the sector on the map of a location (check fire.c).
.burn: defines whether an object can burn (check fire.c).
.weapon: the number of weapons carried by the player (check move.c).
.light: defines whether a location is lit (check misc.c).

emptyRoom is used in several functions, to delete and recall objects from the map.
      (check damage.c, fire.c, misc.c, toggle.c, executeEat)
*/


extern int trigger, flashCountA;

typedef struct object {
   bool         (*condition)(void);
   const char    *description;
   const char    *explanation;
   const char   **tags;
   struct object *location;
   struct object *originalLocation;
   struct object *destination;
   struct object *prospect;
   const char    *details;
   const char    *contents;
   const char    *textGo;
   int            weight;
   int            capacity;
   int            health;
   int            impact;
   int            trust;
   int            power;
   int            animal;
   int            sector;
   int            burn;
   int            weapon;
   int            light;
   const char    *read;
   const char  *(*open)(void);
   const char  *(*close)(void);
   const char  *(*lock)(void);
   const char  *(*unlock)(void);
} OBJECT;

extern OBJECT objs[];

#define player	(objs + 0)
#define gardenEast	(objs + 1)
#define wallGardenEast	(objs + 2)
#define wallGardenEastBurn	(objs + 3)
#define intoPorch	(objs + 4)
#define dirtRoad	(objs + 5)
#define intoGardenNorth	(objs + 6)
#define intoGardenNorthBurn	(objs + 7)
#define car	(objs + 8)
#define wallCar	(objs + 9)
#define gloveCompartment	(objs + 10)
#define snack	(objs + 11)
#define intoCar	(objs + 12)
#define intoGardenEast	(objs + 13)
#define carEngineOff	(objs + 14)
#define carEngineOn	(objs + 15)
#define gardenNorth	(objs + 16)
#define wallGardenNorth	(objs + 17)
#define letter2	(objs + 18)
#define wallGardenNorthBurn	(objs + 19)
#define shed	(objs + 20)
#define wallShedNorth	(objs + 21)
#define screwdriver	(objs + 22)
#define wallShedWest	(objs + 23)
#define wallShedEast	(objs + 24)
#define wallShedBurn	(objs + 25)
#define closedAidKit	(objs + 26)
#define openAidKit	(objs + 27)
#define pillContainer	(objs + 28)
#define pills	(objs + 29)
#define exitGardenNorth	(objs + 30)
#define exitGardenNorthBurn	(objs + 31)
#define intoVegetableGarden	(objs + 32)
#define closedDoorToShed	(objs + 33)
#define openDoorToShed	(objs + 34)
#define closedDoorToGardenNorth	(objs + 35)
#define openDoorToGardenNorth	(objs + 36)
#define vegetableGarden	(objs + 37)
#define wallVegetableGardenSouth	(objs + 38)
#define wallVegetableGardenSouthBurn	(objs + 39)
#define wallVegetableGardenNorth	(objs + 40)
#define raisedBed	(objs + 41)
#define tomatoesBed	(objs + 42)
#define exitVegetableGarden	(objs + 43)
#define exitVegetableGardenBrun	(objs + 44)
#define intoGardenWest	(objs + 45)
#define intoGardenWestBurn	(objs + 46)
#define gardenWest	(objs + 47)
#define wallGardenWest	(objs + 48)
#define intoWoodsNorth	(objs + 49)
#define intoWoodsNorthPlant	(objs + 50)
#define intoWoodsNorthBurn	(objs + 51)
#define keyForGarage	(objs + 52)
#define exitGardenWest	(objs + 53)
#define exitWoodsNorth	(objs + 54)
#define woodsNorth	(objs + 55)
#define wallWoodsNorth	(objs + 56)
#define wallWoodsNorthBurn	(objs + 57)
#define intoWoodsEast	(objs + 58)
#define intoWoodsEastBurn	(objs + 59)
#define intoWoodsWest	(objs + 60)
#define woodsEast	(objs + 61)
#define wallWoodsEast	(objs + 62)
#define wallWoodsEastBurn	(objs + 63)
#define exitWoodsEast	(objs + 64)
#define exitWoodsEastBurn	(objs + 65)
#define bushesWoods	(objs + 66)
#define bushesWoodsNoBerries	(objs + 67)
#define berriesRed	(objs + 68)
#define wallWoodsEastShed	(objs + 69)
#define woodsWest	(objs + 70)
#define wallWoodsWestShiny	(objs + 71)
#define wallWoodsWest	(objs + 72)
#define woodsWestGround	(objs + 73)
#define boxWoods	(objs + 74)
#define pictures	(objs + 75)
#define exitWoodsWest	(objs + 76)
#define intoWoodsSouth	(objs + 77)
#define exitWoodsSouth	(objs + 78)
#define woodsSouth	(objs + 79)
#define wallWoodsSouthWater	(objs + 80)
#define wallWoodsSouth	(objs + 81)
#define intoFieldNorth	(objs + 82)
#define fieldNorth	(objs + 83)
#define wallFieldNorthSlope	(objs + 84)
#define branch	(objs + 85)
#define intoFieldWest	(objs + 86)
#define intoFieldWestBurn	(objs + 87)
#define wallFieldWest	(objs + 88)
#define wallFieldWestBurn	(objs + 89)
#define exitFieldWest	(objs + 90)
#define wallFieldNorth	(objs + 91)
#define wallFieldNorthBurn	(objs + 92)
#define fieldWest	(objs + 93)
#define intoFieldSouth	(objs + 94)
#define fieldSouth	(objs + 95)
#define wallFieldSouth	(objs + 96)
#define wallFieldSouthBurn	(objs + 97)
#define exitFieldSouth	(objs + 98)
#define intoFieldEast	(objs + 99)
#define intoFieldEastBlocked	(objs + 100)
#define fieldEast	(objs + 101)
#define wallFieldEast	(objs + 102)
#define exitFieldEast	(objs + 103)
#define intoGardenSouthGarder	(objs + 104)
#define intoGardenSouthField	(objs + 105)
#define gardenSouth	(objs + 106)
#define wallGardenSouth	(objs + 107)
#define wallGardenSouthBurn	(objs + 108)
#define bushesGarden	(objs + 109)
#define bushesGardenNoBerries	(objs + 110)
#define berriesBlue	(objs + 111)
#define exitGardenSouthGarden	(objs + 112)
#define intoGroveNorth	(objs + 113)
#define exitGardenSouthField	(objs + 114)
#define groveNorth	(objs + 115)
#define wallGroveNorth	(objs + 116)
#define wallGroveNorthBurn	(objs + 117)
#define exitGroveNorth	(objs + 118)
#define intoGroveWest	(objs + 119)
#define groveWest	(objs + 120)
#define wallGroveWest	(objs + 121)
#define wallGroveWestNorth	(objs + 122)
#define wallGroveWestBurn	(objs + 123)
#define letter3	(objs + 124)
#define intoPond	(objs + 125)
#define exitGroveWest	(objs + 126)
#define exitGroveWestBurn	(objs + 127)
#define pond	(objs + 128)
#define wallPond	(objs + 129)
#define bushesPond	(objs + 130)
#define wallPondWater	(objs + 131)
#define mushroom	(objs + 132)
#define exitPond	(objs + 133)
#define intoGroveSouth	(objs + 134)
#define groveSouth	(objs + 135)
#define wallGroveSouth	(objs + 136)
#define wallGroveSouthBurn	(objs + 137)
#define garage	(objs + 138)
#define wallGarage	(objs + 139)
#define wallGarageBurn	(objs + 140)
#define garageBox	(objs + 141)
#define garageBoxBurn	(objs + 142)
#define openDoorToGarage	(objs + 143)
#define closedDoorToGarage	(objs + 144)
#define lockedDoorToGarage	(objs + 145)
#define knife	(objs + 146)
#define exitGroveSouth	(objs + 147)
#define exitGroveSouthBurn	(objs + 148)
#define stoneGarage	(objs + 149)
#define stoneEmpty	(objs + 150)
#define bat	(objs + 151)
#define gas	(objs + 152)
#define matches	(objs + 153)
#define openDoorToGroveSouth	(objs + 154)
#define closedDoorToGroveSouth	(objs + 155)
#define man	(objs + 156)
#define manDead	(objs + 157)
#define manBurn	(objs + 158)
#define porch	(objs + 159)
#define wallPorch	(objs + 160)
#define wallPorchBurn	(objs + 161)
#define intoHouse	(objs + 162)
#define exitPorch	(objs + 163)
#define exitHouse	(objs + 164)
#define exitHouseBurn	(objs + 165)
#define entryway	(objs + 166)
#define wallEntryway	(objs + 167)
#define wallEntrywayBurn	(objs + 168)
#define kitchen	(objs + 169)
#define wallKitchen	(objs + 170)
#define kitchenShelves	(objs + 171)
#define kitchenSink	(objs + 172)
#define openDrawer	(objs + 173)
#define knifeBlock	(objs + 174)
#define knifeBlockEmpty	(objs + 175)
#define knifeShort	(objs + 176)
#define closedFridge	(objs + 177)
#define openFridge	(objs + 178)
#define stove	(objs + 179)
#define rawMeat	(objs + 180)
#define eggsBoiled	(objs + 181)
#define leftover	(objs + 182)
#define wallKitchenWindow	(objs + 183)
#define intoCorridor	(objs + 184)
#define intoKitchen	(objs + 185)
#define exitKitchen	(objs + 186)
#define corridor	(objs + 187)
#define wallCorridor	(objs + 188)
#define exitCorridor	(objs + 189)
#define bloodCorridor	(objs + 190)
#define bedroom	(objs + 191)
#define wallBedroom	(objs + 192)
#define closetBedroom	(objs + 193)
#define clothesBedroom	(objs + 194)
#define bed	(objs + 195)
#define sheets	(objs + 196)
#define pillow	(objs + 197)
#define windowBedroom	(objs + 198)
#define intoBathroom	(objs + 199)
#define intoBedroom	(objs + 200)
#define exitBedroom	(objs + 201)
#define bathroom	(objs + 202)
#define wallBathroom	(objs + 203)
#define wallBathroomWest	(objs + 204)
#define openToilet	(objs + 205)
#define closedToilet	(objs + 206)
#define letter1	(objs + 207)
#define bathroomSink	(objs + 208)
#define mirror	(objs + 209)
#define bathroomSinkEmpty	(objs + 210)
#define mirrorFrame	(objs + 211)
#define trashcan	(objs + 212)
#define vitaminPacket	(objs + 213)
#define vitamin	(objs + 214)
#define exitBathroom	(objs + 215)
#define livingRoom	(objs + 216)
#define livingRoomShelves	(objs + 217)
#define couch	(objs + 218)
#define tvSet	(objs + 219)
#define bookOne	(objs + 220)
#define bookTwo	(objs + 221)
#define bookThree	(objs + 222)
#define windowLivingRoom	(objs + 223)
#define intoLivingRoom	(objs + 224)
#define exitLivingRoom	(objs + 225)
#define closet	(objs + 226)
#define wallCloset	(objs + 227)
#define wallClosetClothes	(objs + 228)
#define lampOff	(objs + 229)
#define shelfCloset	(objs + 230)
#define lampOn	(objs + 231)
#define openDoorToCloset	(objs + 232)
#define closedDoorToCloset	(objs + 233)
#define openDoorToLivingRoom	(objs + 234)
#define closedDoorToLivingRoom	(objs + 235)
#define intoGuestRoom	(objs + 236)
#define guestRoom	(objs + 237)
#define wallGuestRoom	(objs + 238)
#define wallGuestRoomTable	(objs + 239)
#define boxGuestRoom	(objs + 240)
#define vhs	(objs + 241)
#define papers	(objs + 242)
#define battery	(objs + 243)
#define boxJunk	(objs + 244)
#define intoGuestBathoom	(objs + 245)
#define exitGuestRoom	(objs + 246)
#define guestBathroom	(objs + 247)
#define wallGuestBathroom	(objs + 248)
#define closedBoxPhoto	(objs + 249)
#define openBoxPhoto	(objs + 250)
#define darkroomEquipment	(objs + 251)
#define exitGuestBathroom	(objs + 252)
#define wildDog	(objs + 253)
#define wildDogSleep	(objs + 254)
#define wildDogDead	(objs + 255)
#define oldFox	(objs + 256)
#define oldFoxDead	(objs + 257)
#define meat	(objs + 258)
#define emptyRoom	(objs + 259)
#define wallEmptyRoom	(objs + 260)

#define endOfObjs	(objs + 261)

#define validObject(obj)	((obj) != NULL && (*(obj)->condition)())

#define forEachObject(obj)	for (obj = objs; obj < endOfObjs; obj++) if (validObject(obj))
